"""add name column in screen tbl

Revision ID: 399e8833daaf
Revises: cb13e3f05a8f
Create Date: 2020-08-06 16:50:51.375938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399e8833daaf'
down_revision = 'cb13e3f05a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screen', 'name')
    # ### end Alembic commands ###
