"""price in movie_screen tbl

Revision ID: 41ffa56b5142
Revises: 575a167ea437
Create Date: 2020-08-07 21:03:12.860163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ffa56b5142'
down_revision = '575a167ea437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_screen', sa.Column('price', sa.FLOAT(precision=6, asdecimal=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_screen', 'price')
    # ### end Alembic commands ###
