"""added release_date in movie tbl

Revision ID: 455522874124
Revises: 93059aa03ac7
Create Date: 2020-08-07 12:20:34.706808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455522874124'
down_revision = '93059aa03ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'release_date')
    # ### end Alembic commands ###
