"""unique screen name & seat row_letter

Revision ID: 4687bf3c0b86
Revises: 399e8833daaf
Create Date: 2020-08-06 17:43:06.537112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4687bf3c0b86'
down_revision = '399e8833daaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('row_letter', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'row_letter')
    # ### end Alembic commands ###
