"""empty message

Revision ID: 4919300ee587
Revises: 
Create Date: 2020-08-05 22:35:11.916905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4919300ee587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('regular', 'admin', 'super_admin'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('email', name=op.f('uq_account_email'))
    )
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cinema'))
    )
    op.create_table('master_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('launch_datetime', sa.DateTime(), nullable=False),
    sa.Column('phase_out_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_schedule'))
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(precision=7, asdecimal=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(precision=2, asdecimal=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie'))
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Text(), nullable=False),
    sa.Column('total_price', sa.Float(precision=8, asdecimal=2), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('type', name=op.f('uq_payment_type'))
    )
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_province'))
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], name=op.f('fk_city_province_id_province')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head_count', sa.Integer(), nullable=False),
    sa.Column('reserve_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_reservation_account_id_account')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_reservation_payment_id_payment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('play_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('master_schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_schedule_id'], ['master_schedule.id'], name=op.f('fk_schedule_master_schedule_id_master_schedule')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule')),
    sa.UniqueConstraint('master_schedule_id', 'play_datetime', 'end_datetime', name=op.f('uq_schedule_master_schedule_id'))
    )
    op.create_table('screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], name=op.f('fk_screen_cinema_id_cinema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screen'))
    )
    op.create_table('barangay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_barangay_city_id_city')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barangay'))
    )
    op.create_table('movie_screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movie_screen_movie_id_movie')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('fk_movie_screen_schedule_id_schedule')),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], name=op.f('fk_movie_screen_screen_id_screen')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_screen')),
    sa.UniqueConstraint('movie_id', 'screen_id', 'schedule_id', name=op.f('uq_movie_screen_movie_id'))
    )
    op.create_table('seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], name=op.f('fk_seat_screen_id_screen')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat'))
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangay.id'], name=op.f('fk_location_barangay_id_barangay')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.create_table('seat_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('movie_screen_id', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_screen_id'], ['movie_screen.id'], name=op.f('fk_seat_reservation_movie_screen_id_movie_screen')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], name=op.f('fk_seat_reservation_reservation_id_reservation')),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], name=op.f('fk_seat_reservation_seat_id_seat')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_reservation')),
    sa.UniqueConstraint('seat_id', 'reservation_id', 'movie_screen_id', name=op.f('uq_seat_reservation_seat_id'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('contact_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_user_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], name=op.f('fk_user_cinema_id_cinema'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_user_location_id_location'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('movie_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movie_rating_movie_id_movie')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_movie_rating_payment_id_payment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_movie_rating_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_rating'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_rating')
    op.drop_table('user')
    op.drop_table('seat_reservation')
    op.drop_table('location')
    op.drop_table('seat')
    op.drop_table('movie_screen')
    op.drop_table('barangay')
    op.drop_table('screen')
    op.drop_table('schedule')
    op.drop_table('reservation')
    op.drop_table('city')
    op.drop_table('province')
    op.drop_table('payment')
    op.drop_table('movie')
    op.drop_table('master_schedule')
    op.drop_table('cinema')
    op.drop_table('account')
    # ### end Alembic commands ###
