"""release_date in movie tbl

Revision ID: 4a725b585e8a
Revises: 615c75e5afda
Create Date: 2020-08-07 12:18:32.692884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a725b585e8a'
down_revision = '615c75e5afda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'release_date')
    # ### end Alembic commands ###
