"""unique master_schedule, unique movie name

Revision ID: 566159ee2a26
Revises: b9693f24e60d
Create Date: 2020-08-07 17:47:21.678698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566159ee2a26'
down_revision = 'b9693f24e60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_master_schedule_launch_date'), 'master_schedule', ['launch_date', 'phase_out_date'])
    op.create_unique_constraint(op.f('uq_movie_name'), 'movie', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_movie_name'), 'movie', type_='unique')
    op.drop_constraint(op.f('uq_master_schedule_launch_date'), 'master_schedule', type_='unique')
    # ### end Alembic commands ###
