"""add unique screen_id on schedule

Revision ID: 575a167ea437
Revises: 05ad6266e0cd
Create Date: 2020-08-07 18:14:06.977162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575a167ea437'
down_revision = '05ad6266e0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_schedule_screen_id'), 'schedule', ['screen_id', 'master_schedule_id', 'play_time', 'end_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_schedule_master_schedule_id', 'schedule', ['master_schedule_id', 'play_time', 'end_time'], unique=True)
    op.drop_constraint(op.f('uq_schedule_screen_id'), 'schedule', type_='unique')
    # ### end Alembic commands ###
