"""duration column in movie tbl

Revision ID: 615c75e5afda
Revises: 6406814b271a
Create Date: 2020-08-07 12:16:14.002798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '615c75e5afda'
down_revision = '6406814b271a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('duration', sa.Time(), nullable=False))
    op.drop_column('movie', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_column('movie', 'duration')
    # ### end Alembic commands ###
