"""master_schedule updated_at created_at

Revision ID: 854029f35bfa
Revises: 9ef0444fb887
Create Date: 2020-08-07 15:05:16.321543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '854029f35bfa'
down_revision = '9ef0444fb887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_schedule', 'created_at')
    op.drop_column('master_schedule', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_schedule', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('master_schedule', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
