"""seat.row_letter_id

Revision ID: 8959709d78b4
Revises: 8b5ef325cb51
Create Date: 2020-08-06 23:14:50.261825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8959709d78b4'
down_revision = '8b5ef325cb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('row_letter_id', mysql.INTEGER(display_width=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'row_letter_id')
    # ### end Alembic commands ###
