"""check constraint seat_id > capacity

Revision ID: 8b5ef325cb51
Revises: a196e9d10b2e
Create Date: 2020-08-06 23:04:15.379246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5ef325cb51'
down_revision = 'a196e9d10b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("check_id_from_capacity", "seat", "id > screen.capacity")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
