"""remove release_date movie tbl

Revision ID: 93059aa03ac7
Revises: 4a725b585e8a
Create Date: 2020-08-07 12:20:11.243164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93059aa03ac7'
down_revision = '4a725b585e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
