"""phase out date and laund date master_schedule tbl

Revision ID: 9ef0444fb887
Revises: baaba67abe1b
Create Date: 2020-08-07 14:56:45.857305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ef0444fb887'
down_revision = 'baaba67abe1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_schedule', sa.Column('launch_date', sa.Date(), nullable=False))
    op.add_column('master_schedule', sa.Column('phase_out_date', sa.Date(), nullable=False))
    op.drop_column('master_schedule', 'launch_datetime')
    op.drop_column('master_schedule', 'phase_out_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_schedule', sa.Column('phase_out_datetime', mysql.DATETIME(), nullable=False))
    op.add_column('master_schedule', sa.Column('launch_datetime', mysql.DATETIME(), nullable=False))
    op.drop_column('master_schedule', 'phase_out_date')
    op.drop_column('master_schedule', 'launch_date')
    # ### end Alembic commands ###
