"""row_id and unique representation of seat

Revision ID: a196e9d10b2e
Revises: 4687bf3c0b86
Create Date: 2020-08-06 19:17:59.063891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a196e9d10b2e'
down_revision = '4687bf3c0b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('row_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_seat_screen_id'), 'seat', ['screen_id', 'row_id', 'row_letter'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_seat_screen_id'), 'seat', type_='unique')
    op.drop_column('seat', 'row_id')
    # ### end Alembic commands ###
