"""Remove payment tbl

Revision ID: a4ea4549515e
Revises: 32ececd1b613
Create Date: 2020-08-10 13:57:46.485815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4ea4549515e'
down_revision = '32ececd1b613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_rating', sa.Column('reservation_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_movie_rating_reservation_id'), 'movie_rating', ['reservation_id'])
    op.create_foreign_key(op.f('fk_movie_rating_reservation_id_reservation'), 'movie_rating', 'reservation', ['reservation_id'], ['id'])
    op.drop_constraint('fk_movie_rating_payment_id_payment', 'movie_rating', type_='foreignkey')
    op.drop_column('movie_rating', 'payment_id')
    op.add_column('reservation', sa.Column('status', sa.CHAR(length=16), nullable=False))
    op.add_column('reservation', sa.Column('token', sa.String(length=128), nullable=False))
    op.add_column('reservation', sa.Column('total_price', sa.FLOAT(precision=7, asdecimal=2), nullable=False))
    op.drop_constraint('fk_reservation_payment_id_payment', 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'payment_id')
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_reservation_payment_id_payment', 'reservation', 'payment', ['payment_id'], ['id'])
    op.drop_column('reservation', 'total_price')
    op.drop_column('reservation', 'token')
    op.drop_column('reservation', 'status')
    op.add_column('movie_rating', sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_movie_rating_reservation_id_reservation'), 'movie_rating', type_='foreignkey')
    op.create_foreign_key('fk_movie_rating_payment_id_payment', 'movie_rating', 'payment', ['payment_id'], ['id'])
    op.drop_constraint(op.f('uq_movie_rating_reservation_id'), 'movie_rating', type_='unique')
    op.drop_column('movie_rating', 'reservation_id')
    op.create_table('payment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token_id', mysql.TEXT(), nullable=False),
    sa.Column('total_price', mysql.FLOAT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
