"""schedule from datetime to time

Revision ID: baaba67abe1b
Revises: 455522874124
Create Date: 2020-08-07 14:36:40.836662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'baaba67abe1b'
down_revision = '455522874124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('end_time', sa.Time(), nullable=False))
    op.add_column('schedule', sa.Column('play_time', sa.Time(), nullable=False))
    op.create_unique_constraint(op.f('uq_schedule_master_schedule_id'), 'schedule', ['master_schedule_id', 'play_time', 'end_time'])
    op.drop_column('schedule', 'end_datetime')
    op.drop_column('schedule', 'play_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('play_datetime', mysql.DATETIME(), nullable=False))
    op.add_column('schedule', sa.Column('end_datetime', mysql.DATETIME(), nullable=False))
    op.drop_constraint(op.f('uq_schedule_master_schedule_id'), 'schedule', type_='unique')
    op.create_unique_constraint('uq_schedule_master_schedule_id', 'schedule', ['master_schedule_id', 'play_datetime', 'end_datetime'])
    op.drop_column('schedule', 'play_time')
    op.drop_column('schedule', 'end_time')
    # ### end Alembic commands ###
