"""re add screen and master_schedule in schedule tbl

Revision ID: f613575c1fe8
Revises: 1953a4195c04
Create Date: 2020-08-09 19:49:14.848547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f613575c1fe8'
down_revision = '1953a4195c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('master_schedule_id', sa.Integer(), nullable=False))
    op.add_column('schedule', sa.Column('screen_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_schedule_screen_id'), 'schedule', ['screen_id', 'master_schedule_id', 'play_datetime', 'end_datetime'])
    op.create_foreign_key(op.f('fk_schedule_master_schedule_id_master_schedule'), 'schedule', 'master_schedule', ['master_schedule_id'], ['id'])
    op.create_foreign_key(op.f('fk_schedule_screen_id_screen'), 'schedule', 'screen', ['screen_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_schedule_screen_id_screen'), 'schedule', type_='foreignkey')
    op.drop_constraint(op.f('fk_schedule_master_schedule_id_master_schedule'), 'schedule', type_='foreignkey')
    op.drop_constraint(op.f('uq_schedule_screen_id'), 'schedule', type_='unique')
    op.drop_column('schedule', 'screen_id')
    op.drop_column('schedule', 'master_schedule_id')
    # ### end Alembic commands ###
