"""empty message

Revision ID: ff89c2a1dd36
Revises: 3f923782ef98
Create Date: 2020-08-05 23:40:08.359383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff89c2a1dd36'
down_revision = '3f923782ef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('latitude', sa.CHAR(length=16), nullable=True))
    op.add_column('location', sa.Column('longitude', sa.CHAR(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'longitude')
    op.drop_column('location', 'latitude')
    # ### end Alembic commands ###
