"""Not unique type in payment tbl

Revision ID: 32ececd1b613
Revises: d91a71574034
Create Date: 2020-08-09 22:03:11.352505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ececd1b613'
down_revision = 'd91a71574034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payment_type', table_name='payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_payment_type', 'payment', ['type'], unique=True)
    # ### end Alembic commands ###
