"""add cinema_id in movie tbl

Revision ID: 3f9a996af7a6
Revises: 1f6a03e69544
Create Date: 2020-08-08 17:02:34.431391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9a996af7a6'
down_revision = '1f6a03e69544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cinema_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_movie_cinema_id_cinema'), 'movie', 'cinema', ['cinema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_movie_cinema_id_cinema'), 'movie', type_='foreignkey')
    op.drop_column('movie', 'cinema_id')
    # ### end Alembic commands ###
