"""Unique cinema & movie name in movie tbl

Revision ID: 7140d0981e14
Revises: 3f9a996af7a6
Create Date: 2020-08-09 11:52:21.967643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7140d0981e14'
down_revision = '3f9a996af7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_movie_name', 'movie', type_='unique')
    op.create_unique_constraint(op.f('uq_movie_name'), 'movie', ['name', 'cinema_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_movie_name'), 'movie', type_='unique')
    op.create_unique_constraint('uq_movie_name', 'movie', ['name'])
    # ### end Alembic commands ###
