"""added genre column in movie table

Revision ID: 906da5315937
Revises: 9762488226a5
Create Date: 2020-08-19 18:49:11.932715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906da5315937'
down_revision = '9762488226a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genre', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'genre')
    # ### end Alembic commands ###
