"""drop duration

Revision ID: 92c494997849
Revises: 2c34b5db3cd7
Create Date: 2020-08-19 18:05:54.433728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c494997849'
down_revision = '2c34b5db3cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('duration', mysql.TIME(), nullable=False))
    # ### end Alembic commands ###
