"""change duration type into integer

Revision ID: 9762488226a5
Revises: 92c494997849
Create Date: 2020-08-19 18:06:13.453295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9762488226a5'
down_revision = '92c494997849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'duration')
    # ### end Alembic commands ###
