"""drop master_schedule_id in movie_screen tbl

Revision ID: a0b56b3912ce
Revises: a0f1122905d4
Create Date: 2020-08-21 19:49:46.740145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b56b3912ce'
down_revision = 'a0f1122905d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_screen', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.add_column('movie_screen', sa.Column('schedule_id', sa.Integer(), nullable=False))
    op.add_column('movie_screen', sa.Column('screen_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_movie_screen_movie_id'), 'movie_screen', ['movie_id', 'screen_id', 'schedule_id'])
    op.create_foreign_key(op.f('fk_movie_screen_screen_id_screen'), 'movie_screen', 'screen', ['screen_id'], ['id'])
    op.create_foreign_key(op.f('fk_movie_screen_movie_id_movie'), 'movie_screen', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('fk_movie_screen_schedule_id_schedule'), 'movie_screen', 'schedule', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_movie_screen_schedule_id_schedule'), 'movie_screen', type_='foreignkey')
    op.drop_constraint(op.f('fk_movie_screen_movie_id_movie'), 'movie_screen', type_='foreignkey')
    op.drop_constraint(op.f('fk_movie_screen_screen_id_screen'), 'movie_screen', type_='foreignkey')
    op.drop_constraint(op.f('uq_movie_screen_movie_id'), 'movie_screen', type_='unique')
    op.drop_column('movie_screen', 'screen_id')
    op.drop_column('movie_screen', 'schedule_id')
    op.drop_column('movie_screen', 'movie_id')
    # ### end Alembic commands ###
