"""added youtube column in movie table

Revision ID: cc6964695fa6
Revises: 906da5315937
Create Date: 2020-08-20 18:07:33.139108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6964695fa6'
down_revision = '906da5315937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('youtube', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'youtube')
    # ### end Alembic commands ###
