"""price column in movie tbl

Revision ID: ef5c547cfc8f
Revises: 9b6c726c9a9a
Create Date: 2020-08-22 18:13:07.281530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5c547cfc8f'
down_revision = '9b6c726c9a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'price')
    # ### end Alembic commands ###
