"""added master_schedule foreign key in movie_screen tbl

Revision ID: f2ecd27c4e76
Revises: 857ae8c4bc0c
Create Date: 2020-08-21 19:29:06.150519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ecd27c4e76'
down_revision = '857ae8c4bc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_movie_screen_movie_id'), 'movie_screen', ['movie_id', 'screen_id', 'schedule_id', 'master_schedule_id'])
    op.create_foreign_key(op.f('fk_movie_screen_movie_id_movie'), 'movie_screen', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('fk_movie_screen_schedule_id_schedule'), 'movie_screen', 'schedule', ['schedule_id'], ['id'])
    op.create_foreign_key(op.f('fk_movie_screen_screen_id_screen'), 'movie_screen', 'screen', ['screen_id'], ['id'])
    op.create_foreign_key(op.f('fk_movie_screen_master_schedule_id_master_schedule'), 'movie_screen', 'master_schedule', ['master_schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_movie_screen_master_schedule_id_master_schedule'), 'movie_screen', type_='foreignkey')
    op.drop_constraint(op.f('fk_movie_screen_screen_id_screen'), 'movie_screen', type_='foreignkey')
    op.drop_constraint(op.f('fk_movie_screen_schedule_id_schedule'), 'movie_screen', type_='foreignkey')
    op.drop_constraint(op.f('fk_movie_screen_movie_id_movie'), 'movie_screen', type_='foreignkey')
    op.drop_constraint(op.f('uq_movie_screen_movie_id'), 'movie_screen', type_='unique')
    # ### end Alembic commands ###
