"""removed master_schedule table

Revision ID: f6d4179cecaf
Revises: f613575c1fe8
Create Date: 2020-08-09 20:23:45.633915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6d4179cecaf'
down_revision = 'f613575c1fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_schedule_master_schedule_id_master_schedule', 'schedule', type_='foreignkey')
    op.drop_constraint('fk_schedule_screen_id_screen', 'schedule', type_='foreignkey')
    op.drop_index('uq_schedule_screen_id', table_name='schedule')
    op.drop_index('uq_master_schedule_launch_date', table_name='master_schedule')
    op.drop_column('schedule', 'master_schedule_id')
    op.drop_column('schedule', 'screen_id')
    op.drop_table('master_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('master_schedule_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('screen_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_schedule_screen_id_screen', 'schedule', 'screen', ['screen_id'], ['id'])
    op.create_foreign_key('fk_schedule_master_schedule_id_master_schedule', 'schedule', 'master_schedule', ['master_schedule_id'], ['id'])
    op.create_index('uq_schedule_screen_id', 'schedule', ['screen_id', 'master_schedule_id', 'play_datetime', 'end_datetime'], unique=True)
    op.create_table('master_schedule',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('launch_date', sa.DATE(), nullable=False),
    sa.Column('phase_out_date', sa.DATE(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_master_schedule_launch_date', 'master_schedule', ['launch_date', 'phase_out_date'], unique=True)
    # ### end Alembic commands ###
