SELECT_TICKET_QUERY = (
    "SELECT res.id AS 'ticket_id', "
    "c.name AS 'cinema_name', "
    "s.id AS 'screen_id', "
    "m.name AS 'movie_name', "
    "DATE_FORMAT(sch.play_datetime, '%Y-%m-%d %T') AS 'play_datetime', "
    "DATE_FORMAT(sch.end_datetime, '%Y-%m-%d %T') AS 'end_datetime', "
    "CONCAT(COUNT(sr.id), ' x ', sr.price) AS 'price_breakdown', "
    "res.total_price "
    "FROM reservation AS res "
    "JOIN seat_reservation AS sr ON sr.reservation_id = res.id "
    "JOIN movie_screen AS ms ON ms.id = sr.movie_screen_id "
    "JOIN movie AS m ON m.id = ms.movie_id "
    "JOIN screen AS s ON s.id = ms.screen_id "
    "JOIN schedule AS sch ON sch.id = ms.schedule_id "
    "JOIN cinema AS c ON c.id = s.cinema_id "
    "WHERE res.id=:res_id "
    "GROUP BY sr.`reservation_id`"
)
